### ISSUE TITLE
How do I modify its capacity, it is only 1mb

### ISSUE THREAD

**Issue by tangzixiang-hash** [BobVarioa/kjspowah#1]
this is my code
    // .addSolid(fluid, coolness)
	event.addSolid("minecraft:cobblestone", -1000,);

<img width="483" alt="image" src="https://github.com/BobVarioa/kjspowah/assets/60438085/87582e66-d884-4d0f-89a9-13fb78cce3af">

**Comment by tangzixiang-hash** [comment]
![image](https://github.com/BobVarioa/kjspowah/assets/60438085/6a10cad4-0db5-4082-a287-5b1f8ac51c05)

**Comment by BobVarioa** [comment]
Unfortunately, that's not something exposed in the Powah API. Closing this as not planned.
