### ISSUE TITLE
May I ask if this is missing a piece of data

### ISSUE THREAD

**Issue by tangzixiang-hash** [BobVarioa/kjspowah#2]
![image](https://github.com/BobVarioa/kjspowah/assets/60438085/83115235-fcc4-433f-b467-9cc2aabe7325)
There should be another data here, it should be 3, not 2 data, there is one that can be used to calculate the capacity.

**Comment by tangzixiang-hash** [comment]
Because I'm a programming noob, I've always wanted to find the code for this capacity, and then I saw this, please is it.

**Comment by tangzixiang-hash** [comment]
https://discord.com/channels/303440391124942858/1196082703062282290
Someone taught me how to change it, and I can add it like this

**Comment by BobVarioa** [comment]
Ah, I see what I did wrong, I can quickly push a fix for this. Should be out in a couple hours maximum.

**Comment by BobVarioa** [comment]
Actually, this doesn't- ah I missed one of your comments. Yes, this is the intended way to do this.
